# Generated by Django 2.2.19 on 2022-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220211_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Group',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(),
        ),
    ]
